# Generated by Django 3.1.4 on 2021-01-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0002_s_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Registration',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('dep', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('n_pass', models.CharField(max_length=50)),
                ('c_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='S_registration',
        ),
    ]
