# Generated by Django 3.1.4 on 2021-01-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0003_auto_20210102_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='F_Registration',
        ),
    ]
