# Generated by Django 3.1.4 on 2021-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0007_auto_20210105_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='s_name',
            field=models.IntegerField(),
        ),
    ]
