# Generated by Django 3.1.4 on 2021-01-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0009_auto_20210105_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='s_name',
            field=models.IntegerField(max_length=10),
        ),
    ]
