# Generated by Django 3.1.4 on 2021-01-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0011_auto_20210105_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='s_name',
            field=models.CharField(max_length=50),
        ),
    ]
