# Generated by Django 3.1.4 on 2021-01-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0013_f_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f_login',
            old_name='loginpass',
            new_name='c_pass',
        ),
        migrations.RenameField(
            model_name='f_login',
            old_name='loginemail',
            new_name='email',
        ),
    ]
