# Generated by Django 3.1.4 on 2021-02-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0015_s_login_s_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_registration',
            name='b_date',
            field=models.CharField(max_length=50),
        ),
    ]
