# Generated by Django 3.1.4 on 2021-02-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0016_auto_20210203_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_login',
            old_name='c_pass',
            new_name='sc_pass',
        ),
        migrations.RenameField(
            model_name='s_login',
            old_name='email',
            new_name='semail',
        ),
    ]
