# Generated by Django 3.1.4 on 2021-02-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0017_auto_20210204_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_login',
            old_name='sc_pass',
            new_name='c_pass',
        ),
        migrations.RenameField(
            model_name='s_login',
            old_name='semail',
            new_name='email',
        ),
    ]
