# Generated by Django 3.1.4 on 2021-02-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0018_auto_20210204_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
