# Generated by Django 3.1.4 on 2021-02-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0019_capture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='image',
            new_name='snapShot',
        ),
    ]
