# Generated by Django 3.1.4 on 2021-02-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0020_auto_20210204_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='snapShot',
            new_name='image',
        ),
    ]
