# Generated by Django 3.1.4 on 2021-02-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0021_auto_20210204_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='image',
            new_name='btPic',
        ),
    ]
