# Generated by Django 3.1.4 on 2021-02-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0022_auto_20210204_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capturei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='image/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
