# Generated by Django 3.1.4 on 2021-02-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0025_auto_20210208_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f_login',
            old_name='femail',
            new_name='email',
        ),
    ]
