# Generated by Django 3.1.4 on 2021-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0026_auto_20210208_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_login',
            name='s_fname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
