# Generated by Django 3.1.4 on 2021-03-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0029_s_login_s_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_login',
            name='s_fname',
        ),
    ]
