# Generated by Django 3.1.4 on 2021-03-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0030_remove_s_login_s_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_login',
            name='s_fname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
