# Generated by Django 3.1.4 on 2021-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0032_f_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
