# Generated by Django 3.1.4 on 2021-03-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0033_s_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='f_registration',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='s_registration',
            name='s_lname',
        ),
        migrations.RemoveField(
            model_name='s_registration',
            name='subject',
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=10)),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FBSA.semester')),
            ],
        ),
    ]
