# Generated by Django 3.1.4 on 2021-03-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0035_remove_subject_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S_code',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
