# Generated by Django 3.1.7 on 2021-04-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0038_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F_code',
        ),
    ]
