# Generated by Django 3.1.7 on 2021-04-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0040_auto_20210401_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F_code',
        ),
    ]
