# Generated by Django 3.1.7 on 2021-04-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0042_f_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F_Registration',
        ),
    ]
