# Generated by Django 3.1.7 on 2021-04-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0043_delete_f_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Registration',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('n_pass', models.CharField(max_length=50)),
                ('c_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
