# Generated by Django 3.1.4 on 2021-04-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0044_f_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_code',
            name='sub_name',
        ),
    ]
