# Generated by Django 3.1.4 on 2021-04-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FBSA', '0045_remove_f_code_sub_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F_code',
        ),
    ]
